<?php
/**
 * Auto generate class for module Documents
 * 
 * @package      WebGuru3
 * @subpackage   modules/documents/
 * @author       Ondrej Rafaj
 * @author       WebGuruCMS3 Framework CMS admin generator (http://www.webgurucms.com)
 * @version      1.0.0.0
 * @wgversion    3.0.0.0
 * @wgdeveloper  1.0.0.0
 * @since        24. February 2009
 */


class autoGenerateDocuments {
		
	public function __construct() {
		
	}
	
}
?>