<?php
/**
 * Auto generate class for module Databaze dluzniku
 * 
 * @package      WebGuru3
 * @subpackage   modules/databazedluzniku/
 * @author       Ondrej Rafaj
 * @author       WebGuruCMS3 Framework CMS admin generator (http://www.webgurucms.com)
 * @version      1.0.0.0
 * @wgversion    3.0.0.0
 * @wgdeveloper  1.0.0.1
 * @since        9. May 2009
 */


class autoGenerateDatabazedluzniku {
		
	public function __construct() {
		
	}
	
}
?>