<?php
/**
 * Auto generate class for module Dynamic
 * 
 * @package      WebGuru3
 * @subpackage   modules/dynamic/
 * @author       Ondrej Rafaj
 * @author       WebGuruCMS3 Framework CMS admin generator (http://www.webgurucms.com)
 * @version      1.0.0.0
 * @wgversion    3.0.0.0
 * @wgdeveloper  1.0.0.0
 * @since        26. February 2009
 */


class autoGenerateDynamic {
		
	public function __construct() {
		
	}
	
}
?>